import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Poojan Shah",
    template: "%s | Poojan Shah",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth scroll-p-[8rem]">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
